### ISSUE TITLE
Add Notes rollover to display person card notes

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#116]
# Feature Request

**As a** People Allocator
**I would** like to recall any notes I made about a person
**so that** I can consider it when making a decision about their next assignment

## Acceptance Criteria

**If** I hover over a persons name with note icon
**Then** the note should display

### Design
See Erin in the second Product for icon, and Manjusha for the Rollover view:
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=1181%3A3123

## Notes

[Notes.svg.zip](https://github.com/FordLabs/PeopleMover/files/4731294/Notes.svg.zip)

This was something that we had live right before I started, so I'm hoping the code is still in there? It was a little "i" in a circle icon. Changing it to this little note icon. 

It would show up after a persons name when you have a note on them. When you hover over the icon, the note would display. 

Should add in a small delay so that if you're just moving your mouse over the page you don't have things popping up like crazy.

**Comment by malcscott91** [comment]
Split into separate stories for people and product.
