### ISSUE TITLE
Add Sign Out ability (FIX SPACING)

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#119]
# Feature Request

## Story
**As a** People allocator
**I want** to be able to sign out
**So** that I can keep my information secure 

----

## Acceptance Criteria
**Given** I am logged in
**When** I click on the person icon with dropdown arrow in the top right of my screen
**Then** I see the option to Log Out and can click it to no longer be logged into my account. 

## Notes
Logging out should take you back to the home page

**Comment by Druage** [comment]
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=2942%3A0

**Comment by jshaddac** [comment]
1. Im not seeing the icon on the dashboard screen, only once you get to a space. Was that a seperate card? 
2. Theres a really large bottom margin. Can we make that spacing match the spacing within the filter and sort dropdowns?
<img width="186" alt="Screen Shot 2020-06-26 at 2 37 30 PM" src="https://user-images.githubusercontent.com/64792164/85890042-99c75900-b7ba-11ea-97e2-f56a3a7a2e70.png">
