### ISSUE TITLE
ADFS or SSO Log In

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#126]
Jung Koo and Vianney doing this on their project?

**Comment by michaelrygiel** [comment]
https://github.ford.com/FordLabs/crushUI
Example of adfs in angular ^

**Comment by alexwojtala** [comment]
Need to have a team discussion about how to proceed with this. In Authquest or our app?

**Comment by michaelrygiel** [comment]
in our app has been the decision
