### ISSUE TITLE
Move Invite Contributors into Account DropDown

### ISSUE THREAD

**Issue by kschmitt20** [FordLabs/PeopleMover#136]
Invite Contributors is currently a dialog so it needs to be converted into a dropdown so sign out can be added.

**Comment by Druage** [comment]
<img width="209" alt="Screen Shot 2020-06-25 at 9 52 53 AM" src="https://user-images.githubusercontent.com/6293337/85733034-dd8e6580-b6c9-11ea-9cff-692535620858.png">
