### ISSUE TITLE
"Powered by FordLabs" logo should be pinned to the bottom of the screen, but with a top margin so it gets pushed down below the products.

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#145]
Right now it floats up to right under anything on the screen. So if you don't have products yet, it's right at the top.

**Comment by michaelrygiel** [comment]
![Screen Shot 2020-07-16 at 11 37 34 AM](https://user-images.githubusercontent.com/16417259/87691660-d9011e00-c758-11ea-926f-24c3f355024a.png)
