### ISSUE TITLE
Make postman collection for "Add endpoint for sql script db information"

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#148]

**Comment by michaelrygiel** [comment]
https://azureford.sharepoint.com/sites/fordlabs/Members%20Only/Forms/AllItems.aspx?viewid=15439113%2D9858%2D48c2%2D89ce%2Df868f8ee3574&id=%2Fsites%2Ffordlabs%2FMembers%20Only%2FProducts%2FFLIP%2FPeopleMover%2FPostman

**Comment by michaelrygiel** [comment]
only exists in prod2
