### ISSUE TITLE
Fix/Remove flakey tests

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#177]

**Comment by Druage** [comment]
The flaky tests are the two bottom Calendar tests

**Comment by michaelrygiel** [comment]
Combined the two conflicting tests into one. The assumption is that a race condition will not occur if they are one test instead of two concurrent tests. If we have another issue, then delete the test.

File: calendar.test.tsx
Test: 'should have down caret when closed and up arrow when open'
