### ISSUE TITLE
Notify Users When They are given permission to Contribute to a Space

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#179]
# Feature Request

**As a** user of PeopleMover
**I would** like to be notified when I have permission to "contribute/edit" a space
**so that** I am aware of what I can view or edit in a timely fashion

## Acceptance Criteria

If a people allocator gives me edit access to a space, then I should receive an e-mail communicating such.

Constraints on this acceptance criteria:

1. Constraint 1
2. Constraint 2
3. etc

## Notes
Email Design: https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=4069%3A0

Please provide notes on this feature if applicable.

**Comment by kschmitt20** [comment]
ACR/ICR is required to use the Ford approved email service. 

Links below for reference once story is unblocked:
- https://nbt.netops.ford.com/mail/
- https://github.ford.com/DevEnablement/pcfdev-guides/tree/master/email
