### ISSUE TITLE
Choosing a role from existing list using arrow keys

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#182]
# Feature Request

**As a** user of PeopleMover
**I would** like to use the arrow buttons to choose from existing product Roles when Creating a Person
**so that** I don't have to take my hands off the keyboard in the middle of adding a person

## Acceptance Criteria

If I click "Add Person" and begin to type a role, 
Then I should be able to scroll through the existing roles of that space using my arrow keys
And the arrow keys should highlight the roles as I hover over them with my arrow keys
And when I click enter, it should save the role I was hovering over at that time 

Contraints on this acceptance criteria:

1. Constraint 1
2. Constraint 2
3. etc

## **Design**
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=220%3A0

## Notes

Please provide notes on this feature if applicable.

**Comment by tslo11** [comment]
difficulty accessing individual role options
