### ISSUE TITLE
See What Others Are Working On

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#183]
# Feature Request

**As a** person on a product team
**I would** like to see who is working on what product
**so that** I know who I can go to for questions about a product
**and** express specific interest in rotating to another product when time comes to rotate

## Acceptance Criteria
**User Acceptance:**
**Given** I click this link
**Then** I should be able to see the space I am part of without the ability to edit

**PM Acceptance:**
Information on feasibility & effort needed to implement a solution like or similar to this so we can determine best way to show product teams where they fall on a space.

SPIKE Questions:

Can we create a URL that shares today snapshot - does not allow visitors to make any changes
Can we create a URL that shares entire space (all dates on calendar) - but does not allow visitors to make any changes?

**Comment by alexwojtala** [comment]
We decided to move forward with generating a link to give view only access
