### ISSUE TITLE
Archived Products only appear as such from that day onwards

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#189]
# Feature Request

**As a** People Allocator
**I would** like to go back to previous dates in the past and see a snapshot of all the active products at that time, even the archived ones
**so that** I can develop an accurate view of the Space at that time

## Acceptance Criteria

**If** a product is active on 7/7
**And** I archive it on 7/15
**And** I go back to the space on date 7/7
**Then** that product should not be listed as archived on the space for that date

## Notes

Please talk to Jenny/Sara for quick explanation before beginning this story.

**Comment by sabdul14** [comment]
Team discussed and removing the Archive checkbox should solve the problem outlined in this story.

**Comment by tslo11** [comment]
Story complete, but 'archive' as a field in the Product object remains in the code. Keeping it and all the associated logic in there until we settle on how we want to use it in the future.
