### ISSUE TITLE
Change product start date (Bob) 

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#197]
# Feature Request

**As a** People allocator
**I would** like to change the product start date to later date without losing any of people card
**so that** I don't lose track of anyone

## Acceptance Criteria

> _If I change the start date A to later date B, anyone who had moved to that product prior to later date B will remain on their original product until the changed start date B_

**Comment by tslo11** [comment]
editProduct endpoint:
if startDate is moved into future:
- find assignments for that product between new and old startDates. change effective date to new startDate
- assignments moving off product?
