### ISSUE TITLE
Add Hover to "Sort By:" Dropdown

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#207]
# Feature Request

**As a** People Allocator
**I would** like to see hover states on what I'm mousing over
**so that** it's clear what I'm mousing over

## Acceptance Criteria

> _If I mouse over/hover over the words in the "Sort By:" Dropdown, I should see the same hover style as I do in the account dropdown_

## Design

https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=3452%3A110

**Comment by RandomAshes** [comment]
We added the hover to the sort toggle itself, the sort dropdown that was mentioned in the ticket, the filter toggle, and the filter dropdown checkboxes, btw. Just to keep things consistent.

**Comment by smle225** [comment]
- Resizing the sort by dropdown container to show all words
- Changing the 'Name' to Alphabetical'
