### ISSUE TITLE
Move Jenkins on Openshift v4

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#213]
# Feature Request

Needs to be done before 9/4

**As a** description of the the user of this feature
**I would** description of the feature capabilities
**so that** justification for the feature

## Acceptance Criteria

> _If I do A B should happen_

Contraints on this acceptance criteria:

1. Constraint 1
2. Constraint 2
3. etc

## Notes

Consistent testing, reduces flakey tests, 
Large: Because unaware of how much effort it could be? Longer set of steps? Don't know how to do it? when does it make sense to do this by? is it urgent?

**Comment by kschmitt20** [comment]
Waiting on a response from Lee D to help onboard Peoplemover to Openshift V4
