### ISSUE TITLE
X out of end date (and start date)

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#217]
# Context

Users can no longer X out of the end date field. This story brings that ability back by adding X outside of start date and end date box.

# Feature Request

**As a** PeopleMover user
**I would** like the ability to X out the end date 
**so that** I can remove an end date in case the one I initially set has changed and I no longer know when the end date will be 

## Acceptance Criteria

**Given** I set an end date in a product
**When** I try to remove the end date
**Then** I have an X button to the right of the field that I can click to remove it
**And** I have an X button to the right of the start date field 

## Design
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=4263%3A72

## Notes

Because Chrome has removed the ability for us to have an X button in the end date field, we have decided to add one to the right of the field. For consistency purposes, we added the same design to the start date too.

**Comment by alexwojtala** [comment]
Branch exists for this story 217__product-form-date-reset

**Comment by michaelrygiel** [comment]
Story is in stage, I forgot to pull request it in
