### ISSUE TITLE
Edit Space Name

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#222]
# Feature Request

## Story
**As a** PeopleMover user
**I want** to be able to edit a space name 
**So** that I can edit mistakenly named spaces or change them based on organizational name changes

----

## Acceptance Criteria

**Given**  I create a space
**When** I click the elipses on the modal in the dashboard
**And** an Edit option appears
**And** it changes color when I hover over it
**And** a modal appears when I click Edit
**And** I can edit the space name and click Save
**Then** the modal on the dashboard is updated with the new space name

## Design

https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=4990%3A170

**Comment by smle225** [comment]
- Hover state missing
- Should we reconsider the "Last modified" state? Should it reflect the time when space name was edited too?
