### ISSUE TITLE
Typing date bug

### ISSUE THREAD

**Issue by smle225** [FordLabs/PeopleMover#230]
# Feature Request

## Story
**As a** People Allocater
**I want** to be able to manually type start date and end date 
**So** that I have the flexibility to either click the date picker or easily type the date I would like

----

## Acceptance Criteria
**Given**  I want to add/edit my start or/and end date
**When** I want to type instead of picking a date
**Then** Date should be present without giving me without wierd errors

## Notes
- Currently, datepicker lets me type any numbers or words without giving me any warnings. However it prevents from me to save 

- @vwillot & @michaelrygiel know what to do :)

**Comment by michaelrygiel** [comment]
https://reactdatepicker.com/

**Comment by sabdul14** [comment]
Below changes requested upon discussion with Sharon, Mike, Vianney, Sara

Calendar Icon always defaulted for start date.
Calendar Icon for End Date when an End Date has not been chosen
X Icon for End Date once an end date has been populated
Center the X Icon
