### ISSUE TITLE
Download Report

### ISSUE THREAD

**Issue by malcscott91** [FordLabs/PeopleMover#25]
# Feature Request

## Story
**As a** people allocator
**I want** to have an easy way to see my reports
**So** I can view or share them

----

## Acceptance Criteria
**Given** I'm in my space
**When** I click the "Download Report" button
**Then** my report automatically downloads as a csv file

## Notes
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=2942%3A0

User should be able to collect the same data points that were collected in the reporting function in PROD1.

**Comment by tslo11** [comment]
report columns:
- remove boardName
- reorder: [a] productName, [b] personRole, [c] personName

**Comment by smle225** [comment]
- personName should come before personRole (we can discuss more about this with John and the team)
- productName should be in alpathetical order

**Comment by sabdul14** [comment]
There are two Download Report Buttons - just need one :)
