### ISSUE TITLE
Why can't we have special characters in space name (URL)?

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#281]
# Feature Request

**As a** product manager
**I would** like to understand why a space is not created when the name includes special characters & unique symbols
**so that** I can determine if we should solve that problem or solve for the current flow

## Acceptance Criteria

Enough information on effort needed to EITHER:
-  Allow special characters & unique symbols in successful creation of a space OR
- Continue not allowing special characters and instituting a solution that involves informing the user they cannot create a space with those characters + gray out "Add Space" button

## Notes

Can we have lower case letters?
Can we have spaces within space name?

**Comment by willot** [comment]
We can save special characters in the database ©©˙®´¨˙©¨∫. The issue come from the url parsing. Only a limited special characters are allowed. 
2 options:
-use a regex to limit characters
-use random ids for space url and let users give the name they want including spaces and capital letters, under 255 characters
