### ISSUE TITLE
Pros & Cons: Space name unique vs. not unique

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#282]
# Feature Request

**As a** product manager
**I would** like to know the ramifications of making space name NOT unique
**so that** I can determine the best way to communicate the limitations of peoplemover naming conventions to our users

## Acceptance Criteria

Have enough information on effort, benefits, & consequences to make a decision around: 
- continuing on current flow and keeping the space name unique (letting the user know when a name has been taken) OR
- making the space name not unique (allowing several users create their own spaces with the same names)

## Notes

What if user wants to edit the name of their space later on? How does that affect URL?

**Comment by alexwojtala** [comment]
We decided that we will be making space names not unique and will be using some sort of guid in the url
