### ISSUE TITLE
Last Modified Date

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#353]
# Feature Request

**As a** product manager
**I would** like to know what triggers a change in last modified date
**so that** I know if we are communicating changes appropriately to our user

## Acceptance Criteria

Constraints on this acceptance criteria:

## Notes
This is in reference to the last modified date that is reflected in the space modals on the dashboard.

**Comment by RandomAshes** [comment]
Once PR to update currentTimeStamp is merged, all of these actions update the space last modified:

- Add/Edit/Delete Product
- Add/Delete/Edit Person
- Add/Edit/Delete Role
- Edit/Delete Product Tag (NOT Add)
- Add/Edit/Delete Location
-Add/Cancel Assignments
