### ISSUE TITLE
"Role" & "Assign To" dropdown in alphabetical order

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#355]
# Feature Request

**As a** peoplemover user
**I would** like all dropdowns to be presented in alphabetical order
**so that** my expectations around consistent design across the app are met 

## Acceptance Criteria

**Given** I am in the edit person modal
**When** I click the "Role" & "Assign To" dropdowns
**Then** the options are presented in alphabetical order

Constraints on this acceptance criteria:

**Comment by smle225** [comment]
There should be no distinction between upper and lower case
