### ISSUE TITLE
Reassigned drawer should have revert option on individual people

### ISSUE THREAD

**Issue by malcscott91** [FordLabs/PeopleMover#36]
# Feature Request

## Context
Add the link to revert people to make it really easy to cancel changes that were made

## Story
**As a** People Allocator
**I want** an easy way to cancel an assignment change
**So** that I feel I can play with the schedule and then easily change it back

----

## Acceptance Criteria
**Given** I want to cancel an assignment change
**When** I look at the reassignment window and see my person that changed
**Then** I can click the revert link and they would move back to whatever product they were on the day before. 

## Notes
**Design:** https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=1181%3A3123

**Comment by tslo11** [comment]
for newly created people (no previous assignments):
- if unassigned: do not show in reassigned drawer
- if assigned directly to a product: show "Assigned to <product>." revert --> send to unassigned, do not show in reassigned drawer.
