### ISSUE TITLE
List of PeopleMover Users & Space

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#360]
# Feature Request
I can no longer track all of the users on PeopleMover on my own as a PM, I need a reliable source of truth.

**As a** product manager
**I would** like the ability to pull up information on all users and spaces in PeopleMover
**so that** I am equipped with the right information to react quickly when there is an issue in production

**Data Needed:**

- List of all spaces
Who created that space (cdsid)
Users who have access to that space (cdsid)

- List of all users

## Acceptance Criteria

Output of this card could be the various ways to generate above data. Once all options are presented, PM can choose one and will create a card to work on it.

Eventually, I see myself wanting access to more information in the future and adding to above data set.

**Comment by kschmitt20** [comment]
Discussed with Sara and new cards were created for how we are going to move forward providing the necessary data.
