### ISSUE TITLE
Update "Last Modified Date"

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#365]
# Feature Request

**As a** peoplemover user
**I would** like to know when my space was last modified
**so that** I can recall when changes are made to my space

## Acceptance Criteria

**Given** I edit space name
**Then** last modified date is updated

**Given** I add a product tag
**Then** last modified date is updated

## Notes

Here are the list of actions that currently trigger an update to Last Modified Date: 

- Add/Edit/Delete Product
- Add/Delete/Edit Person
- Add/Edit/Delete Role
- Edit/Delete Product Tag (NOT Add)
- Add/Edit/Delete Location
- Add/Cancel Assignments
- Add Space (NOT Edit)
- Archive/Unarchive Product

**Comment by smle225** [comment]
Every list reflects last modified accept 'Cancel Assignment'
