### ISSUE TITLE
Update Front-End Apache Licenses

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#383]
# Feature Request

**As a** peoplemover engineer
**I would** like all apache licenses to be updated from 2019 to 2020
**so that** I am in compliance

## Acceptance Criteria
Typescript files have apache header at top of it - update from 2019 to 2020. If does not have it, add it.

## Notes

Replace Copyright Ford 2019 with Copyright 2020 on the front end

**Comment by RandomAshes** [comment]
Looks like the front end was already updated, but the backend wasn't. I'll put in a PR to update all that are left.
