### ISSUE TITLE
Fix Filter

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#400]
# Feature Request
Currently, the filter dropdown acts as an OR, when choosing multiple data points to filter on. It should be acting as an AND.

**As a** peoplemover user
**I would** like filter to act like an appropriate filter that I would use on any other website
**so that** I am not confused by the functionality of this feature

## Acceptance Criteria

**Given** I am in a space
**When** I click a one dataset on the filter dropdown
**Then** I click another dataset on the filter dropdown
**Then** only the products with BOTH datasets appear

**Comment by willot** [comment]
Criteria inside location act as a OR
criteria inside product tag act as a OR
Criteria inside role act as a OR

criteria between location and product tag act as a AND
criteria for role is independent location and product tag (product need to exist)
