### ISSUE TITLE
My Roles: CTA for check mark and x

### ISSUE THREAD

**Issue by smle225** [FordLabs/PeopleMover#425]
# Feature Request

**As a** peoplemover user
**I would** like a neater experience when creating roles
**so that** I am not confused by several line breaks (currently)

## Acceptance Criteria

**Given** I am in a space
**When** I click My Roles
**Then** I see the new My Roles Modal
**And** when I click on edit icon, two boxes appear around role name and color
**And** all of the edit & trash icons associated with other roles disappear when I am in edit mode
**And** an X and check mark icon appear on the right side of the role
**And** the X icon exits out of edit mode without saving
**And** the check icon saves the changes to the role
**And** when I leave edit mode, the edit icon and trash icon appear for the other roles

## Design
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=5297%3A0

**Comment by willot** [comment]
There is a problem when the name of the new role is too long. 
![Screen Shot 2020-10-13 at 11 51 50 AM](https://user-images.githubusercontent.com/8730126/95885560-5c77de80-0d4b-11eb-914b-8c4b483a466e.png)
