### ISSUE TITLE
My Roles: UI Changes

### ISSUE THREAD

**Issue by smle225** [FordLabs/PeopleMover#427]
# Feature Request

**As a** peoplemover user
**I would** like a neater experience when creating roles
**so that** I am not confused by several line breaks (currently)

## Acceptance Criteria

**Given** I am in a space
**When** I click My Roles
**Then** I see the new My Roles Modal
**And** when I see edit & trash icons next to each role
**And** the edit and trash icons are hoverable and change color when you hover over it
**And** overall font size increased to 14 px
**And** edit and trashcan icon increased to 18 x 18
**And** add new role CTA font size incrased to 14 px, bolded
**And** add new role CTA has filled in + icon 

## Design
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=5297%3A191

**Comment by michaelrygiel** [comment]
https://featurebranchui.apps.pd01i.edc1.cf.ford.com/
