### ISSUE TITLE
Minor UI Changes: Filter & Sort by dropdown

### ISSUE THREAD

**Issue by smle225** [FordLabs/PeopleMover#442]
# Feature Request

**As a** peoplemover user
**I would** like a consistent experience overall dropdown
**so that** it's more satisfying and not confusing

## Acceptance Criteria

**Given** I am in a space
**When** I click **'Filter'**
**Then** I see the filter dropdown
**And** when I scroll to see more filter options, scroll bar on the dropdown is skewed to left

## Notes
Remove the right padding on filter dropdown or replace the scroll bar to the right? 

## Acceptance Criteria

**Given** I am in a space
**When** I click **'Sort by'**
**Then** I see the sort by dropdown
**And** make it similar to account dropdown 

## Notes
Add the vertical padding for sort by dropdown (16px)

**Comment by sabdul14** [comment]
Ready to push to stage
