### ISSUE TITLE
Email Notification for Those Invited to Space

### ISSUE THREAD

**Issue by malcscott91** [FordLabs/PeopleMover#46]
# Feature Request

## Context
Related to #317 Once a user chooses who they want to invite to their space. Those people will receive an email notification with a link to sign in or sign up to PeopleMover and have access to the space they were invited to.

## Story
**As a** people allocator
**I want** the people who I invite to my space to receive an email notification
**So** that they know they have access to PeopleMover
**And** know how to to get to the space to sign in/sign up

----

## Acceptance Criteria
**Given** I input valid emails on the "Invite" space
**When** my invitee receive an email
**Then** they will be will given a link to sign in/sign up to my PeopleMover space
*And* the link tied to the user mail can only be used once

**Comment by michaelrygiel** [comment]
Should this wait until we decide whats gonna happen with ADFS?
