### ISSUE TITLE
Determine Metrics Strategy

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#471]
# Feature Request
As a PM, I expect to be working very closely with the pair that picks up this story.

**As a** Product Manager
**I would** like to be informed about engagement on PeopleMover in an easily consumable way
**so that** I can speak intelligently about our user-base, engagement levels, & have available data to leverage when performing experiments 

## Acceptance Criteria

The outcome of this SPIKE is to:
- Determine if Matomo can give us the information we need based on criteria in Notes.
- If we cannot configure Matomo to give us the information we need based on criteria in Notes determine what other systems we can use.
- Enough information to create stories that execute on the agreed upon strategy

## Notes

![image](https://user-images.githubusercontent.com/67916138/96300331-54c26f00-0fc3-11eb-8d40-585f7f1581e1.png)

**Comment by griffico** [comment]
[ ] Story for adding space name to app title
