### ISSUE TITLE
CTA buttons (Accessibility)

### ISSUE THREAD

**Issue by smle225** [FordLabs/PeopleMover#479]
**As a** peoplemover user
**I would** like the Cancel & Save buttons to have focus states
**so that** I am visually aware of what field I am in , should I choose to use the keyboard or screen reader to navigate the website

## Acceptance Criteria

**Given** I am in a space
**When** I click My Roles, My Tags, Assign a person, Create new person, Create new product, Edit product
**And** I use keyboard to 'Cancel' or 'Save'
**Then** it shows what field I am focused in
**And**  I can understand what I'm selecting with a screen reader or keyboard

# Notes
 * Text field focus state borderline color to #5463B0

**Comment by michaelrygiel** [comment]
My roles and My tags are being refactored. Wait for that story to be completed and in stage before proceeding

**Comment by sabdul14** [comment]
Focus ring appearing on Location field & Product Tag field., calendar fields.
