### ISSUE TITLE
Microsoft Edge: Authentication Issue for some users

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#509]
# Bug

Edge keeps asking specific users for authentication over and over again.

#### Issue description
Two users, DF& AR expressed that they keep being asked for authentication on Edge. Sara asked them to use Chrome instead. Then, team created a page that lets users who open PeopleMover in Edge know that they should use Chrome instead.

Even after this page was pushed to production, a third user, KM expressed that "the app won’t load at all in Microsoft Edge.  Only Chrome.  Edge just keeps asking for authentication over and over again."

#### Steps to reproduce the issue
This only occurs for specific users. We cannot reproduce the issue if you access PeopleMover with Edge and have no issues.

1.  
2. 
3. 

#### What's the expected result?

Users should be able to access PeopleMover without being asked to authenticate over and over again. 

#### What's the actual result?

-Once this card is picked up, I can reach out to one of the above users (NOT AR ) and ask them to show us what they are seeing.

#### Additional details / screenshot

- ![Screenshot]()
-

**Comment by sabdul14** [comment]
Edge Version 86.0 works - Ihor Debryn used it and had no issues. Sara to look into versions being used by the users who had loop issues.

**Comment by sabdul14** [comment]
Meeting setup with Dustin Fern - user who had this issue on Wednesday 11/4 at 11 AM. Alex will forward to whoever he is pairing with on that day.

**Comment by alexwojtala** [comment]
Alex Wojtala has Windows and Edge version 86.0.622.58 did work, OFF VPN
Alex Wojtala has Mac and Edge version 86.0.622.58 did work, OFF and ON VPN
