### ISSUE TITLE
Move e2e tests and api tests to only github actions, and keep only ui unit tests and linting in the pre commit hook

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#549]
# Feature Request

Move e2e tests and api tests to a ~pre push git hook~ only github actions, and keep only ui unit tests and linting in the pre commit hook

## Notes

Note out of retro 11/13/20.

**Comment by aclift19Ford** [comment]
So, it looks like we can't even do this as the npm package we use to start up our cypress tests has an issue with husky's pre-push command. >.< 

https://github.com/bahmutov/start-server-and-test/issues/285
