### ISSUE TITLE
Tall Modals get cut off at top and bottom

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#63]
# Feature Request

## Context
If any of our modals are taller than the size of your screen, they get cut off at the top and bottom. Making them hard to save or close. The browswer should scroll to allow us to see the whole modal.

## Story
**As a** People Allocator
**I want** to be able to see my entire modal
**So** that I have all of the options - including being able to close or save the modal

----

## Acceptance Criteria
**Given** I am in a modal 
**When** That modal is taller than the size of the screen
**Then** It automatically makes the screen size taller so that the page will scroll and keep some space (32 or 48 px?) above and below the modal.

## Notes
The whole page behind doesnt have to scroll, just the overlay area. Assuming that it's easier if everything just scrolls together though.

There is a double scroll on PC - unsure if this will be resolved with this story. If not, create new story.

![image](https://user-images.githubusercontent.com/67916138/87456481-00c77900-c5d5-11ea-859a-e8faed6f9bf0.png)

**Comment by sabdul14** [comment]
@jshaddac Does the image I uploaded capture the issue correctly?
