### ISSUE TITLE
Add "Sort By Product Tag" Feature

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#67]
# Feature Request

## Context
Users who use the boards for things other than time will now be using product tags to easily look at things similarly to how they do now. The ability to sort by those product tags will make it easier for them to look between their different buckets instead of having to filter one and then the other. 

This is just to add the ability to sort by Product Tag, not the design where they're seperated out. 

## Story
**As a** People Allocator
**I want** to be able to see my products arranged by product tag
**So** that I can scrill through and see them all but keep them seperated still. 

----

## Acceptance Criteria
**Given** I am in my space
**When** I click the Sort By dropdown
**Then** I see an option to sort by product tag
**And** if I click it then i see my products sorted that way

## Notes
Push with #103 

## Design
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=3443%3A0

**Comment by michaelrygiel** [comment]
Friday todo:
- Move sort logic out of productReducer and into productList
- Ensure the above change does not negatively affect other components using the products array
- Create tests and product tag logic in productList

**Comment by alexwojtala** [comment]
Can be reviewed here: https://67-product-sortui.apps.pd01i.edc1.cf.ford.com/
