### ISSUE TITLE
Creating a space with spaces in it, should still allow you to navigate to the space

### ISSUE THREAD

**Issue by tslo11** [FordLabs/PeopleMover#73]
When you create a space that includes a space (i.e "Space One") then when you click on the space in the user dashboard it should take you to the URl ....../space%20one. Right now it is broken because it is /space one

**Comment by jshaddac** [comment]
@kschmitt20 since you were the last one to move this... How do I test this since we made it so that you CAN'T add spaces. Do we have any existing spaces with a space (the character) or is this one kind of redundant now?
