### ISSUE TITLE
Add ability to duplicate an existing space

### ISSUE THREAD

**Issue by johnrozan** [FordLabs/peoplemover#748]
Feature Request
As a user of peoplemover
I want the ability to clone an existing space
so that I can easily use it for prospective changes or split off new teams without having to reenter information

Acceptance Criteria
From the opening screen of PeopleMover (which lists all the user's current spaces), a user will be able to click the three menu dots. In addition to the current Edit option, a user will also be able to select "Duplicate space" which will create a copy of the existing space. On click of Duplicate space, the screen of available spaces will reload and the the new screen will now have an additional space with the name of the copied space listed as "[Space name] Duplicate"

Duplicating a board menu:
![image](https://user-images.githubusercontent.com/95775450/145473219-eceb2a11-d87a-4872-a921-bdc655cc8d89.png)

State when board has been duplicated:
![image](https://user-images.githubusercontent.com/95775450/145474720-8f403b1c-65e6-48d4-b8b8-761607f6ce0f.png)

Currently the ownership and editorship details remain the same for the duplicated board

Accessiblity Criteria
 Text and background color meets a minimum color contrast ratio of 4.5:1
 All non-text content (e.g. images, icon) has alt text
 Web page includes appropriate headings to communicate structure/hierarchy (h1>h2>h3)
 All functionality is available to a keyboard
 Focus styles are highly visible
 Tab order is logical and aligns with the visual order
 Voice over is understandable and logical
 Aria labels are added to elements with no visible text
 Decorative elements (e.g. non-informative icons) are hidden from screen readers
 Form fields have appropriately coded labels that are visible during input
 Links are visually identifiable and have a clear focus and active state
Notes

**Comment by rescoto-int** [comment]
Myself and a colleague are close to ready to submit a PR for this. However, we don't seem to have the ability to open a branch for said PR. Are we requiring specific access rights being granted?

**Comment by sapphon** [comment]
> Myself and a colleague are close to ready to submit a PR for this. However, we don't seem to have the ability to open a branch for said PR. Are we requiring specific access rights being granted?

Hello!  Connor from FordLabs here.

There is no branch protection on the PeopleMover repo except of the 'main' branch.  After checking the places I know to look, I can see no reason why you should not be able to create and push up a new branch for your PR.

My role isn't IT or support, but I will try to assist you.  Could you perhaps provide more information, including console output, re: what you've tried and what the results have been?

**Comment by rescoto-int** [comment]
I have attempted to create a branch using the git command line and receive
an error that I am unable to perform that action. As well, I go to the
branches area on the web view of the project and no Create new branch
option shows.

**Comment by RandomAshes** [comment]
Closing issue as this feature has now been added. :)
