### ISSUE TITLE
[1/2 Day] Investigate tools for creating End to End tests.

### ISSUE THREAD

**Issue by tslo11** [FordLabs/PeopleMover#75]
**As a user** I don't want the site to be down when I visit it.

**As an engineer** I want an easy way to tell if users can perform basic user flow tests to make sure basic interactions are available to users

Outcome is cards to implement end to end tests for PeopleMover

**Comment by malcscott91** [comment]
Team had meeting and discussed. Action Item for Malcolm or Jenny: Come up with main work flows of what the user should be able to do.

**Comment by alexwojtala** [comment]
https://ui.vision/

**Comment by jshaddac** [comment]
How do these workflows sound?:

> - Change date –> create new product –> drag person onto it 
> - Create new person –> create new role for them –> assign them to product 
> - Open “My Roles” Modal –> Edit Role –> Change color and name 
> - Open “My Tags” Modal –> Edit Product Tag –> Edit Location Tag 
> - Edit Product –> Create new Product Tag –> Change Start Date
