### ISSUE TITLE
View Only does not work after 7pm est (12am utc)

### ISSUE THREAD

**Issue by johnrozan** [FordLabs/peoplemover#762]
Bug
Issue description
This issue needs to be reproduced, not sure if it still exists.

Our product is now used by people all over earth. The view only works by making a request by asking to see the data of today. But sometimes the server and the front end are not in the same time zone. So when a user is asking for the view only at 9pm eastern time the server is on utc time and therefore on a different day. The request fail because view only can only show data for today.

Steps to reproduce the issue
Go to View Only link at 7 pm EST
Blank error page appears
What's the expected result?
View Only should always work and show the current day of the visitor (based on the time zone that the visitor is in)

What's the actual result?
Additional details / screenshot

**Comment by reneeliken** [comment]
Went to View Only link at 10:30pm EST
No blank error page occurred; View Only appeared as normal and showed current day for my timezone.
