### ISSUE TITLE
IF QUICK: Fix EVERYONE being moved to reassigned when a new board is created from copying another

### ISSUE THREAD

**Issue by tslo11** [FordLabs/PeopleMover#77]
# Feature Request

## Context
Currently when copying a board to create a new one, EVERYONE is moved to reassigned. It would be nice if that didn't happen. 

## Story
**As a** People Allocator
**I want** my reassigned window to be totally empty when I create a new board from copying another
**So** I can keep track of the changes i actually do make after copying thigns over

----

## Acceptance Criteria
**Given** Am in my space
**When** I create a new board by copying another
**Then** my reassigned window on the new board should be empty

## Notes
Please only play this story if it turns out to be pretty quick OR if we realize calendar is going to take quite a long time.

**Comment by alexwojtala** [comment]
Turned out not to be a quick fix
