### ISSUE TITLE
PeopleMover Branding in AuthQuest Email

### ISSUE THREAD

**Issue by malcscott91** [FordLabs/PeopleMover#82]
# Feature Request

## Context
In the current state, any emails received from AuthQuest have no reference to PeopleMover. This can confuse users who are not familiar and they may wonder if its from a valid source.

## Story
**As a** People Allocator 
**I want** to see PeopleMover branding in the emails I receive when signing up
**So** that I know the email came from PeopleMover

----

## Acceptance Criteria
**Given** I sign up
**When** I open an email from AuthQuest
**Then** I can see wording, colors, and themes of PeopleMover

## Design
**Email Verification:** https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=3523%3A70

**Comment by Druage** [comment]
We will need to add a few columns to the AuthQuest settintgs table:

1. primaryColor
2. email image
3. email sender
