### ISSUE TITLE
Make "Good" Password Criteria Visible for Sign Up

### ISSUE THREAD

**Issue by malcscott91** [FordLabs/PeopleMover#83]
# Feature Request

## Context
In the current state, when a user is coming up with their initial password or resetting password they are shown a color inidicator that lets them know if their pasword is strong or weak. However the criteria for what makes a strong password is not shown.

## Story
**As a** People Allocator
**I want** see what makes a password strong
**So** that I can easily create my password without issues

----

## Acceptance Criteria
**Given** I'm creating my account
**When** I go in to type my initial or reset password
**Then** I am shown the critiera for a strong password

## Design
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=2891%3A765

**Comment by malcscott91** [comment]
Reach out to John Handy for Ford password criteria

**Comment by jshaddac** [comment]
https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=2891%3A765
