### ISSUE TITLE
Add PeopleMover Branding to Sign up/in process

### ISSUE THREAD

**Issue by malcscott91** [FordLabs/PeopleMover#84]
# Feature Request

## Context
In the current state, there is no reference to PeopleMover in the sign up or log in process. This could be confusing to the user, because they are not sure exactly what they are signing up for.

## Story
**As a** People Allocator
**I want** to see PeopleMover branding throughout the sign up / log in process
**So** I know exactly what product I'm using

----

## Acceptance Criteria
**Given** I'm signing up for PeopleMover or logging in
**When** I'm on the sign up or log in page
**Then** I see PeopleMover colors, themes, and wording.

## Design
**Sign Up:** https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=2891%3A765

**Email Verified / Login:** https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=3523%3A102

**Log In:** https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=3523%3A187

**Comment by Druage** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/6293337/81981462-51831b80-95fe-11ea-8b7c-447f3c141e40.png">

**Comment by alexwojtala** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/16964807/81981560-77a8bb80-95fe-11ea-90fa-3538541db4cb.png">

**Comment by alexwojtala** [comment]
Need to set size to 0 when there is no content for logo

**Comment by Druage** [comment]
These two issues have been fixed!
