### ISSUE TITLE
Implement Security for Backend Endpoints

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#98]
# Feature Request
We need to secure back-end so that we can make PeopleMover accessible off of VPN

**As a** product manager 
**I would** like confidence that our site is secure
**so that** we can make PeopleMover accessible off of VPN per feedback from our uesrs 

## Acceptance Criteria

**Given** I hit any critical endpoint
**Then** I am required to provide a OAuth token
**So that** I can be checked against permissions to edit that space
**And** I am who I say I am

List all endpoints.

**Comment by malcscott91** [comment]
Good example on how this is done on RetroQuest

**Comment by michaelrygiel** [comment]
Should this be done after ADFS?
